#!/bin/sh

PYWAL()
{
  WAL_VARS()
  {
    COLORLIST=~/.cache/wal/colors
    XRESOURCES=~/.cache/wal/colors.dmenu.Xresources
  }
  
  # These are the colors.
  WAL_COLORS()
  {
    COLOR_01=$(sed -n 10,10p $COLORLIST)
    COLOR_02=$(sed -n 1,1p $COLORLIST)
    COLOR_03=$(sed -n 6,6p $COLORLIST)
    COLOR_04=$(sed -n 4,4p $COLORLIST)
  }

  WAL_WRITE()
  {
    echo "!!dmenu" > $XRESOURCES
    echo "dmenu.background:       $COLOR_01" >> $XRESOURCES
    echo "dmenu.foreground:       $COLOR_02" >> $XRESOURCES
    echo "dmenu.selbackground:    $COLOR_03" >> $XRESOURCES
    echo "dmenu.selforeground:    $COLOR_04" >> $XRESOURCES
  }
  
  WAL_SET()
  {
  # Pywal
  test /usr/bin/xrdb && test ~/.cache/wal/colors.dmenu.Xresources || touch ~/.cache/wal/colors.dmenu.Xresources
  test ~/.cache/wal/colors.Xresources && xrdb -query | grep "color66" && printf "Using pywal" && xrdb -merge ~/.cache/wal/colors.dmenu.Xresources
  }

  WAL_VARS
  WAL_COLORS
  WAL_WRITE
  WAL_SET
}

case "$1" in
"-r") PYWAL ; exit 0 ;;
"") test /usr/bin/dmenu && test ~/.cache/wal/colors.dmenu.Xresources && xrdb -merge ~/.cache/wal/colors.dmenu.Xresources ;;
esac

# Run dmenu
dmenu_path | dmenu "$@" | ${SHELL:-"/bin/sh"} &
rm -f $HOME/.cache/dmenu_run
